#!/bin/bash
# copy
if [ -d dist ]
then
  rm -fR dist
fi

mkdir dist
cp ./src/* dist

# load config
. ./scripts/config $1 $2

# sed
sed -i s/%%BUCKET%%/$BUCKET/g dist/*
sed -i s/%%TABLE%%/$TABLE/g dist/*
sed -i s/%%IDENTITY_POOL_ID%%/$IDENTITY_POOL_ID/g dist/*
sed -i s,%%LOGIN%%,$LOGIN,g dist/*
sed -i s,%%CLIENT_ID%%,$CLIENT_ID,g dist/*
sed -i s/%%REGION%%/$REGION/g dist/*
